// <auto-generated />
using System;
using Hammer.Auction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hammer.Auction.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260325051333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.KamcoAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApslAsesAvgAmt")
                        .HasColumnType("bigint")
                        .HasColumnName("apsl_ases_avg_amt");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<string>("CltrImgFiles")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cltr_img_files");

                    b.Property<string>("CltrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cltr_nm");

                    b.Property<long>("CltrNo")
                        .HasColumnType("bigint")
                        .HasColumnName("cltr_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<int>("IqryCnt")
                        .HasColumnType("integer")
                        .HasColumnName("iqry_cnt");

                    b.Property<string>("LdnmAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ldnm_adrs");

                    b.Property<long>("MinBidPrc")
                        .HasColumnType("bigint")
                        .HasColumnName("min_bid_prc");

                    b.Property<string>("NmrdAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("nmrd_adrs");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<string>("PbctCltrStatNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pbct_cltr_stat_nm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UscbdCnt")
                        .HasColumnType("integer")
                        .HasColumnName("uscbd_cnt");

                    b.HasKey("Id")
                        .HasName("pk_kamco_auction_items");

                    b.HasIndex("CtgrFullNm")
                        .HasDatabaseName("ix_kamco_auction_items_ctgr_full_nm");

                    b.HasIndex("MinBidPrc")
                        .HasDatabaseName("ix_kamco_auction_items_min_bid_prc");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cls_dtm");

                    b.HasIndex("PbctCltrStatNm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cltr_stat_nm");

                    b.HasIndex("PlnmNo", "PbctNo", "CltrNo")
                        .IsUnique()
                        .HasDatabaseName("ix_kamco_auction_items_plnm_no_pbct_no_cltr_no");

                    b.ToTable("kamco_auction_items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
