// <auto-generated />
using System;
using Hammer.Auction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hammer.Auction.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260328160659_AddQuiz")]
    partial class AddQuiz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.InstitutionAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BidDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bid_dvsn_cd");

                    b.Property<string>("BidDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bid_dvsn_nm");

                    b.Property<string>("BidMtdCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bid_mtd_cd");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<string>("CtgrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_id");

                    b.Property<string>("DpslMtdCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dpsl_mtd_cd");

                    b.Property<string>("DpslMtdNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dpsl_mtd_nm");

                    b.Property<string>("OrgNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("org_nm");

                    b.Property<string>("OrgPlnmNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("org_plnm_no");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<DateTimeOffset>("PbctExctDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_exct_dtm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<string>("PlnmDt")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("plnm_dt");

                    b.Property<string>("PlnmKindCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plnm_kind_cd");

                    b.Property<string>("PlnmKindNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plnm_kind_nm");

                    b.Property<string>("PlnmMnmtNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plnm_mnmt_no");

                    b.Property<string>("PlnmNm")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("plnm_nm");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<string>("PrptDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prpt_dvsn_cd");

                    b.Property<string>("PrptDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prpt_dvsn_nm");

                    b.Property<string>("TotAmtUnpcDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tot_amt_unpc_dvsn_cd");

                    b.Property<string>("TotAmtUnpcDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tot_amt_unpc_dvsn_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_institution_auction_items");

                    b.HasIndex("CtgrId")
                        .HasDatabaseName("ix_institution_auction_items_ctgr_id");

                    b.HasIndex("OrgNm")
                        .HasDatabaseName("ix_institution_auction_items_org_nm");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_institution_auction_items_pbct_cls_dtm");

                    b.HasIndex("PlnmNo", "PbctNo")
                        .IsUnique()
                        .HasDatabaseName("ix_institution_auction_items_plnm_no_pbct_no");

                    b.ToTable("institution_auction_items", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.KamcoAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApslAsesAvgAmt")
                        .HasColumnType("bigint")
                        .HasColumnName("apsl_ases_avg_amt");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<string>("CltrImgFiles")
                        .HasColumnType("text")
                        .HasColumnName("cltr_img_files");

                    b.Property<string>("CltrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cltr_nm");

                    b.Property<long>("CltrNo")
                        .HasColumnType("bigint")
                        .HasColumnName("cltr_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<int>("IqryCnt")
                        .HasColumnType("integer")
                        .HasColumnName("iqry_cnt");

                    b.Property<string>("LdnmAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ldnm_adrs");

                    b.Property<long>("MinBidPrc")
                        .HasColumnType("bigint")
                        .HasColumnName("min_bid_prc");

                    b.Property<string>("NmrdAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("nmrd_adrs");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<string>("PbctCltrStatNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pbct_cltr_stat_nm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UscbdCnt")
                        .HasColumnType("integer")
                        .HasColumnName("uscbd_cnt");

                    b.HasKey("Id")
                        .HasName("pk_kamco_auction_items");

                    b.HasIndex("CtgrFullNm")
                        .HasDatabaseName("ix_kamco_auction_items_ctgr_full_nm");

                    b.HasIndex("MinBidPrc")
                        .HasDatabaseName("ix_kamco_auction_items_min_bid_prc");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cls_dtm");

                    b.HasIndex("PbctCltrStatNm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cltr_stat_nm");

                    b.HasIndex("PlnmNo", "PbctNo", "CltrNo")
                        .IsUnique()
                        .HasDatabaseName("ix_kamco_auction_items_plnm_no_pbct_no_cltr_no");

                    b.ToTable("kamco_auction_items", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.OnbidCodeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrHirkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_hirk_id");

                    b.Property<string>("CtgrHirkNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_hirk_nm");

                    b.Property<string>("CtgrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_id");

                    b.Property<string>("CtgrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_onbid_code_infos");

                    b.HasIndex("CtgrId")
                        .IsUnique()
                        .HasDatabaseName("ix_onbid_code_infos_ctgr_id");

                    b.ToTable("onbid_code_infos", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.Quiz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Choice1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("choice1");

                    b.Property<string>("Choice2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("choice2");

                    b.Property<string>("Choice3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("choice3");

                    b.Property<string>("Choice4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("choice4");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer")
                        .HasColumnName("correct_index");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("explanation");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.ToTable("quizzes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Choice1 = "공매는 공공기관이, 경매는 법원이 진행한다",
                            Choice2 = "공매는 법원이, 경매는 공공기관이 진행한다",
                            Choice3 = "공매와 경매는 동일한 절차이다",
                            Choice4 = "공매는 부동산만, 경매는 동산만 취급한다",
                            CorrectIndex = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "공매는 한국자산관리공사(KAMCO) 등 공공기관이 체납세금 등의 사유로 압류한 재산을 매각하는 절차이고, 경매는 법원이 채권자의 신청에 따라 진행하는 강제집행 절차입니다.",
                            Question = "공매와 경매의 가장 큰 차이점은 무엇인가요?"
                        },
                        new
                        {
                            Id = 2L,
                            Choice1 = "감정평가서 확인",
                            Choice2 = "회원가입 및 공동인증서 등록",
                            Choice3 = "입찰보증금 납부",
                            Choice4 = "현장 답사",
                            CorrectIndex = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "온비드에서 입찰에 참여하려면 먼저 회원가입을 하고 공동인증서(구 공인인증서)를 등록해야 합니다. 이후 물건 검색, 입찰보증금 납부, 입찰서 제출 순으로 진행됩니다.",
                            Question = "온비드에서 입찰에 참여하기 위한 첫 번째 단계는?"
                        },
                        new
                        {
                            Id = 3L,
                            Choice1 = "낙찰자가 대금을 납부한 상태",
                            Choice2 = "입찰자가 없거나 최저가 미달로 매각이 이루어지지 않은 것",
                            Choice3 = "입찰이 성공적으로 완료된 상태",
                            Choice4 = "물건이 취소된 상태",
                            CorrectIndex = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "유찰이란 입찰에 참여한 사람이 없거나, 입찰가가 최저입찰가에 미달하여 매각이 성립되지 않은 것을 말합니다. 유찰되면 차회 공매 시 최저입찰가가 인하될 수 있습니다.",
                            Question = "공매에서 '유찰'이란 무엇을 의미하나요?"
                        },
                        new
                        {
                            Id = 4L,
                            Choice1 = "감정가와 최저입찰가는 항상 동일하다",
                            Choice2 = "최저입찰가는 감정가보다 항상 높다",
                            Choice3 = "최저입찰가는 감정가 이하로 설정되며, 유찰 시 더 낮아질 수 있다",
                            Choice4 = "감정가는 입찰과 무관하다",
                            CorrectIndex = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "감정가는 감정평가사가 산정한 물건의 가치이고, 최저입찰가는 이를 기준으로 설정됩니다. 첫 공매 시 감정가의 일정 비율로 시작하며, 유찰될 때마다 단계적으로 인하됩니다.",
                            Question = "감정가와 최저입찰가의 관계로 올바른 것은?"
                        },
                        new
                        {
                            Id = 5L,
                            Choice1 = "7일 이내",
                            Choice2 = "30일 이내",
                            Choice3 = "60일 이내",
                            Choice4 = "90일 이내",
                            CorrectIndex = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "공매 낙찰 후 잔금은 일반적으로 납부기한 내(통상 60일)에 납부해야 합니다. 기한 내 미납 시 매각결정이 취소되고 입찰보증금이 국고에 귀속됩니다.",
                            Question = "공매 낙찰 후 잔금 납부 기한은 일반적으로 얼마인가요?"
                        },
                        new
                        {
                            Id = 6L,
                            Choice1 = "5%",
                            Choice2 = "10%",
                            Choice3 = "20%",
                            Choice4 = "30%",
                            CorrectIndex = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "공매 입찰보증금은 최저입찰가의 10%입니다. 입찰보증금은 입찰 전에 납부해야 하며, 유찰되거나 낙찰되지 않은 경우 환불됩니다.",
                            Question = "공매 입찰 시 입찰보증금은 최저입찰가의 몇 %인가요?"
                        },
                        new
                        {
                            Id = 7L,
                            Choice1 = "물건의 색상을 확인하기 위해",
                            Choice2 = "낙찰 후에도 소멸되지 않는 권리(임차권, 유치권 등)가 있을 수 있기 때문",
                            Choice3 = "입찰가를 자동으로 계산해주기 때문",
                            Choice4 = "세금을 면제받기 위해",
                            CorrectIndex = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "권리분석은 해당 물건에 설정된 저당권, 가압류, 임차권, 유치권 등을 파악하는 과정입니다. 낙찰 후에도 소멸되지 않는 권리가 있으면 추가 비용이 발생할 수 있어 반드시 사전에 확인해야 합니다.",
                            Question = "공매 물건의 '권리분석'이 중요한 이유는?"
                        },
                        new
                        {
                            Id = 8L,
                            Choice1 = "아파트",
                            Choice2 = "토지",
                            Choice3 = "자동차",
                            Choice4 = "상가건물",
                            CorrectIndex = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Explanation = "자동차는 '동산'으로 분류됩니다. 부동산은 토지, 주거용 건물(아파트, 주택 등), 상가 및 업무용 건물 등을 포함합니다.",
                            Question = "다음 중 공매에서 '부동산'에 해당하지 않는 것은?"
                        });
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.RealEstateTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("area");

                    b.Property<int?>("BuildYear")
                        .HasColumnType("integer")
                        .HasColumnName("build_year");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("building_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DealAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("deal_amount");

                    b.Property<int>("DealDay")
                        .HasColumnType("integer")
                        .HasColumnName("deal_day");

                    b.Property<int>("DealMonth")
                        .HasColumnType("integer")
                        .HasColumnName("deal_month");

                    b.Property<int>("DealYear")
                        .HasColumnType("integer")
                        .HasColumnName("deal_year");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<string>("Jibun")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jibun");

                    b.Property<string>("LawdCd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lawd_cd");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<string>("UmdNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("umd_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_real_estate_trades");

                    b.HasIndex("LawdCd")
                        .HasDatabaseName("ix_real_estate_trades_lawd_cd");

                    b.HasIndex("PropertyType")
                        .HasDatabaseName("ix_real_estate_trades_property_type");

                    b.HasIndex("DealYear", "DealMonth", "DealDay")
                        .HasDatabaseName("ix_real_estate_trades_deal_year_deal_month_deal_day");

                    b.HasIndex("LawdCd", "PropertyType", "Jibun", "DealYear", "DealMonth", "DealDay", "Area")
                        .IsUnique()
                        .HasDatabaseName("ix_real_estate_trades_lawd_cd_property_type_jibun_deal_year_de");

                    b.ToTable("real_estate_trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
