// <auto-generated />
using System;
using Hammer.Auction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hammer.Auction.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20260326084503_AddInstitutionAuctionAndCodeInfo")]
    partial class AddInstitutionAuctionAndCodeInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.InstitutionAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BidDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bid_dvsn_cd");

                    b.Property<string>("BidDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bid_dvsn_nm");

                    b.Property<string>("BidMtdCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bid_mtd_cd");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<string>("CtgrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_id");

                    b.Property<string>("DpslMtdCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dpsl_mtd_cd");

                    b.Property<string>("DpslMtdNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dpsl_mtd_nm");

                    b.Property<string>("OrgNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("org_nm");

                    b.Property<string>("OrgPlnmNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("org_plnm_no");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<DateTimeOffset>("PbctExctDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_exct_dtm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<string>("PlnmDt")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("plnm_dt");

                    b.Property<string>("PlnmKindCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plnm_kind_cd");

                    b.Property<string>("PlnmKindNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plnm_kind_nm");

                    b.Property<string>("PlnmMnmtNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plnm_mnmt_no");

                    b.Property<string>("PlnmNm")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("plnm_nm");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<string>("PrptDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prpt_dvsn_cd");

                    b.Property<string>("PrptDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prpt_dvsn_nm");

                    b.Property<string>("TotAmtUnpcDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tot_amt_unpc_dvsn_cd");

                    b.Property<string>("TotAmtUnpcDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tot_amt_unpc_dvsn_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_institution_auction_items");

                    b.HasIndex("CtgrId")
                        .HasDatabaseName("ix_institution_auction_items_ctgr_id");

                    b.HasIndex("OrgNm")
                        .HasDatabaseName("ix_institution_auction_items_org_nm");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_institution_auction_items_pbct_cls_dtm");

                    b.HasIndex("PlnmNo", "PbctNo")
                        .IsUnique()
                        .HasDatabaseName("ix_institution_auction_items_plnm_no_pbct_no");

                    b.ToTable("institution_auction_items", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.KamcoAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApslAsesAvgAmt")
                        .HasColumnType("bigint")
                        .HasColumnName("apsl_ases_avg_amt");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<string>("CltrImgFiles")
                        .HasColumnType("text")
                        .HasColumnName("cltr_img_files");

                    b.Property<string>("CltrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cltr_nm");

                    b.Property<long>("CltrNo")
                        .HasColumnType("bigint")
                        .HasColumnName("cltr_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<int>("IqryCnt")
                        .HasColumnType("integer")
                        .HasColumnName("iqry_cnt");

                    b.Property<string>("LdnmAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ldnm_adrs");

                    b.Property<long>("MinBidPrc")
                        .HasColumnType("bigint")
                        .HasColumnName("min_bid_prc");

                    b.Property<string>("NmrdAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("nmrd_adrs");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<string>("PbctCltrStatNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pbct_cltr_stat_nm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UscbdCnt")
                        .HasColumnType("integer")
                        .HasColumnName("uscbd_cnt");

                    b.HasKey("Id")
                        .HasName("pk_kamco_auction_items");

                    b.HasIndex("CtgrFullNm")
                        .HasDatabaseName("ix_kamco_auction_items_ctgr_full_nm");

                    b.HasIndex("MinBidPrc")
                        .HasDatabaseName("ix_kamco_auction_items_min_bid_prc");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cls_dtm");

                    b.HasIndex("PbctCltrStatNm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cltr_stat_nm");

                    b.HasIndex("PlnmNo", "PbctNo", "CltrNo")
                        .IsUnique()
                        .HasDatabaseName("ix_kamco_auction_items_plnm_no_pbct_no_cltr_no");

                    b.ToTable("kamco_auction_items", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.OnbidCodeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrHirkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_hirk_id");

                    b.Property<string>("CtgrHirkNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_hirk_nm");

                    b.Property<string>("CtgrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_id");

                    b.Property<string>("CtgrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_onbid_code_infos");

                    b.HasIndex("CtgrId")
                        .IsUnique()
                        .HasDatabaseName("ix_onbid_code_infos_ctgr_id");

                    b.ToTable("onbid_code_infos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
