// <auto-generated />
using System;
using Hammer.Auction.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hammer.Auction.Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.InstitutionAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BidDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bid_dvsn_cd");

                    b.Property<string>("BidDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bid_dvsn_nm");

                    b.Property<string>("BidMtdCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bid_mtd_cd");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<string>("CtgrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_id");

                    b.Property<string>("DpslMtdCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dpsl_mtd_cd");

                    b.Property<string>("DpslMtdNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dpsl_mtd_nm");

                    b.Property<string>("OrgNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("org_nm");

                    b.Property<string>("OrgPlnmNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("org_plnm_no");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<DateTimeOffset>("PbctExctDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_exct_dtm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<string>("PlnmDt")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("plnm_dt");

                    b.Property<string>("PlnmKindCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plnm_kind_cd");

                    b.Property<string>("PlnmKindNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plnm_kind_nm");

                    b.Property<string>("PlnmMnmtNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plnm_mnmt_no");

                    b.Property<string>("PlnmNm")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("plnm_nm");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<string>("PrptDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prpt_dvsn_cd");

                    b.Property<string>("PrptDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("prpt_dvsn_nm");

                    b.Property<string>("TotAmtUnpcDvsnCd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tot_amt_unpc_dvsn_cd");

                    b.Property<string>("TotAmtUnpcDvsnNm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tot_amt_unpc_dvsn_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_institution_auction_items");

                    b.HasIndex("CtgrId")
                        .HasDatabaseName("ix_institution_auction_items_ctgr_id");

                    b.HasIndex("OrgNm")
                        .HasDatabaseName("ix_institution_auction_items_org_nm");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_institution_auction_items_pbct_cls_dtm");

                    b.HasIndex("PlnmNo", "PbctNo")
                        .IsUnique()
                        .HasDatabaseName("ix_institution_auction_items_plnm_no_pbct_no");

                    b.ToTable("institution_auction_items", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.KamcoAuctionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApslAsesAvgAmt")
                        .HasColumnType("bigint")
                        .HasColumnName("apsl_ases_avg_amt");

                    b.Property<string>("BidMtdNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bid_mtd_nm");

                    b.Property<string>("CltrImgFiles")
                        .HasColumnType("text")
                        .HasColumnName("cltr_img_files");

                    b.Property<string>("CltrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cltr_nm");

                    b.Property<long>("CltrNo")
                        .HasColumnType("bigint")
                        .HasColumnName("cltr_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrFullNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_full_nm");

                    b.Property<int>("IqryCnt")
                        .HasColumnType("integer")
                        .HasColumnName("iqry_cnt");

                    b.Property<string>("LdnmAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ldnm_adrs");

                    b.Property<long>("MinBidPrc")
                        .HasColumnType("bigint")
                        .HasColumnName("min_bid_prc");

                    b.Property<string>("NmrdAdrs")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("nmrd_adrs");

                    b.Property<DateTimeOffset>("PbctBegnDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_begn_dtm");

                    b.Property<DateTimeOffset>("PbctClsDtm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pbct_cls_dtm");

                    b.Property<string>("PbctCltrStatNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pbct_cltr_stat_nm");

                    b.Property<long>("PbctNo")
                        .HasColumnType("bigint")
                        .HasColumnName("pbct_no");

                    b.Property<long>("PlnmNo")
                        .HasColumnType("bigint")
                        .HasColumnName("plnm_no");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UscbdCnt")
                        .HasColumnType("integer")
                        .HasColumnName("uscbd_cnt");

                    b.HasKey("Id")
                        .HasName("pk_kamco_auction_items");

                    b.HasIndex("CtgrFullNm")
                        .HasDatabaseName("ix_kamco_auction_items_ctgr_full_nm");

                    b.HasIndex("MinBidPrc")
                        .HasDatabaseName("ix_kamco_auction_items_min_bid_prc");

                    b.HasIndex("PbctClsDtm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cls_dtm");

                    b.HasIndex("PbctCltrStatNm")
                        .HasDatabaseName("ix_kamco_auction_items_pbct_cltr_stat_nm");

                    b.HasIndex("PlnmNo", "PbctNo", "CltrNo")
                        .IsUnique()
                        .HasDatabaseName("ix_kamco_auction_items_plnm_no_pbct_no_cltr_no");

                    b.ToTable("kamco_auction_items", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read")
                        .HasFilter("is_read = false");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.NotificationSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_settings");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_settings_user_id");

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.OnbidCodeInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CtgrHirkId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_hirk_id");

                    b.Property<string>("CtgrHirkNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_hirk_nm");

                    b.Property<string>("CtgrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ctgr_id");

                    b.Property<string>("CtgrNm")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ctgr_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_onbid_code_infos");

                    b.HasIndex("CtgrId")
                        .IsUnique()
                        .HasDatabaseName("ix_onbid_code_infos_ctgr_id");

                    b.ToTable("onbid_code_infos", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<long?>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<int>("SelectedIndex")
                        .HasColumnType("integer")
                        .HasColumnName("selected_index");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_quiz_attempts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_quiz_attempts_user_id");

                    b.HasIndex("UserId", "QuizId")
                        .HasDatabaseName("ix_quiz_attempts_user_id_quiz_id");

                    b.ToTable("quiz_attempts", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.RealEstateTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Area")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("area");

                    b.Property<int?>("BuildYear")
                        .HasColumnType("integer")
                        .HasColumnName("build_year");

                    b.Property<string>("BuildingName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("building_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DealAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("deal_amount");

                    b.Property<int>("DealDay")
                        .HasColumnType("integer")
                        .HasColumnName("deal_day");

                    b.Property<int>("DealMonth")
                        .HasColumnType("integer")
                        .HasColumnName("deal_month");

                    b.Property<int>("DealYear")
                        .HasColumnType("integer")
                        .HasColumnName("deal_year");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<string>("Jibun")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("jibun");

                    b.Property<string>("LawdCd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("lawd_cd");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer")
                        .HasColumnName("property_type");

                    b.Property<string>("UmdNm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("umd_nm");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_real_estate_trades");

                    b.HasIndex("LawdCd")
                        .HasDatabaseName("ix_real_estate_trades_lawd_cd");

                    b.HasIndex("PropertyType")
                        .HasDatabaseName("ix_real_estate_trades_property_type");

                    b.HasIndex("DealYear", "DealMonth", "DealDay")
                        .HasDatabaseName("ix_real_estate_trades_deal_year_deal_month_deal_day");

                    b.HasIndex("LawdCd", "PropertyType", "Jibun", "DealYear", "DealMonth", "DealDay", "Area")
                        .IsUnique()
                        .HasDatabaseName("ix_real_estate_trades_lawd_cd_property_type_jibun_deal_year_de");

                    b.ToTable("real_estate_trades", (string)null);
                });

            modelBuilder.Entity("Hammer.Auction.Domain.Entities.SearchLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("keyword");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_search_logs");

                    b.HasIndex("Keyword")
                        .HasDatabaseName("ix_search_logs_keyword");

                    b.HasIndex("SearchedAt")
                        .HasDatabaseName("ix_search_logs_searched_at");

                    b.HasIndex("UserId", "SearchedAt")
                        .HasDatabaseName("ix_search_logs_user_id_searched_at");

                    b.ToTable("search_logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
